name: Build

on: push

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update
    - run: sudo apt install --fix-missing libguestfs-tools virtualbox qemu-kvm libvirt-daemon-system
    - run: sudo chmod +r /boot/*
    - run: sudo chmod 0666 /dev/kvm
    - run: make
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          debian-12-text.qcow2
          debian-12-text.vdi
          debian-12.qcow2
          debian-12.vdi
          run
